app/main/__init__.py
from flask import Blueprint

main=Blueprint('main',__name__)

from . import views,forms

app/main/views.py
from flask import render_template,request,redirect,url_for,flash
from flask_login import current_user,login_required
from app.models import Election, User
from . import main
from werkzeug.utils import secure_filename
import os
from ..request import get_elections, get_posts_count_for_all_elections,get_candidates_for_all_posts_per_election, get_posts_per_election, has_voted_all_posts,vote_for_candidate,get_all_election_winners,get_votes_for_all_posts,get_active_elections


ALLOWED_EXTENSIONS={'png','jpg','jpeg','gif'}

@main.route('/')
def index():
  if current_user.is_authenticated and current_user.role_id==2:
    return redirect(url_for('admin.admin_view')) 
  elif current_user.is_authenticated and current_user.role_id==1:
    return redirect(url_for('main.home'))
  else:
    return render_template('main/index.html')

@main.route('/student')
def student():
  return render_template('main/student.html',title='Student')  

@main.route('/home')
@login_required
def home():
  election_list=get_active_elections()
  post_count=get_posts_count_for_all_elections()
  return render_template('main/home.html',election_list=election_list,post_count=post_count)

@main.route('/election/<id>/vote')
def vote(id):
  election=Election.query.filter_by(id=id).first()
  posts=get_posts_per_election(id)
  all_candidates=get_candidates_for_all_posts_per_election(id)
  vote_status=has_voted_all_posts(current_user.id,id)

  election_winners={}
  election_posts_results={}
  if election.status=='closed':
    election_winners=get_all_election_winners(election.id)
    election_posts_results=get_votes_for_all_posts(election.id)

  return render_template('main/vote.html',election=election,all_candidates=all_candidates,posts=posts,vote_status=vote_status,election_winners=election_winners,election_posts_results=election_posts_results)

@main.route('/election/<id>/vote/post/<post_id>/candidate/<candidate_id>')
def cast_vote(id,post_id,candidate_id):
  vote_for_candidate(current_user.id,post_id,candidate_id)
  flash('Vote success','success')

  return redirect(url_for('main.vote',id=id))



def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@main.route('/user/<user_name>/profile',methods=['GET','POST'])
def profile(user_name):

  user=User.query.filter_by(id=current_user.id).first()
  if request.method=='POST':
    photo=request.files['photo']
    if photo and allowed_file(photo.filename):
      filename=secure_filename(photo.filename)
      photo.save(os.path.join('app/static/photos',filename))
      user.profile_pic_path=f'photos/{filename}'
      user.save_user()
      flash('Update Successful','success')
    else:
      flash('Please provide a valid file','error')

  return render_template('main/profile/profile.html')

app/templates/main/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link rel="stylesheet" href="{{url_for('static',filename='css/main/footer.css')}}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    

</head>
<body>
<!--footer starts from here-->
<footer class="footer">
<div class="container bottom_border">
<div class="row">
<div class=" col-sm-4 col-md col-sm-4  col-12 col">
<h5 class="headin5_amrc col_white_amrc pt2">Find us</h5>
<!--headin5_amrc-->
<p class="mb10">The easiest application that allows students to vote for a candidate in a post in a school election.
</p>
<p><i class="fa fa-location-arrow"></i> 9878/25 sec 9 rohini 35 </p>
<p><i class="fa fa-phone"></i>  +91-9999878398  </p>
<p><i class="fa fa fa-envelope"></i> info@example.com  </p>


</div>



<div class=" col-sm-4 col-md  col-12 col">
<h5 class="headin5_amrc col_white_amrc pt2">Follow us</h5>
<!--headin5_amrc ends here-->

<ul class="footer_ul2_amrc">
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p><a href="#">https://www.lipsum.com/</a></p></li>
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p><a href="#">https://www.lipsum.com/</a></p></li>
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p><a href="#">https://www.lipsum.com/</a></p></li>
</ul>
<!--footer_ul2_amrc ends here-->
</div>
</div>
</div>



<!--foote_bottom_ul_amrc ends here-->
<p class="text-center">Copyright @2022 | by <a href="#">Group 1</a></p>

<ul class="social_footer_ul">
<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
<li><a href="#"><i class="fab fa-twitter"></i></a></li>
<li><a href="#"><i class="fab fa-linkedin"></i></a></li>
<li><a href="#"><i class="fab fa-instagram"></i></a></li>
</ul>
<!--social_footer_ul ends here-->
</div>

</footer>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

app/templates/main/home.html
{% extends 'auth/base.html' %}
{% import 'main/macros.html' as macro %}
{% block nav %}
{% include 'auth/navbar.html' %}
{% endblock %}
{% block content %}

<div class="container">
  <h1 class="text-center"><span id="act">Active</span>&nbsp<span id="election">Election</span><img src="{{url_for('static',filename='asset-images/hand-voting-ballot-box-icon-260nw-1342666157.jpg')}}" style="height: 50px; width:50px;"></h1>


{{macro.displayElections(election_list,post_count)}}
</div>

{% endblock %}

app/templates/main/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Uwazi Poll</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</head>

<body>
    <header class="homepage-header">
        <div class="container">
            <nav class="d-flex justify-content-between">
                <img src="{{url_for('static',filename='asset-images/vote_icon.png')}}" alt="">
                <h1 class="pt-5 fw-bold"><span class="uwazi-title"> UWAZI</span> <span class="poll-title"> POLL</span></h1>
            </nav>
            <div class="login-options d-flex justify-content-center">
                <a href="{{url_for('auth.login')}}" class="btn btn-primary mx-5 px-5">Student</a>
                <a href="{{url_for('auth.admin_login')}}" class="btn btn-danger mx-5 px-5">Admin</a>
            </div>
        </div>
    </header>
</body>

</html>

app/templates/main/macros.html
{% macro displayElections(election_list,post_count) %}

{% if election_list %}

{% for election in election_list%}
<div class="card m-5 shadow border-0">

  <div class="d-flex justify-content-around m-3 p-3">
    <span class="blue-title">Start Time: {{election.start_time}}</span> 
    <span class="red-title">End Time: {{election.end_time}}</span></div>

    <div class="d-flex justify-content-around align-items-center m-5 p-3 shadow">
      <span># {{election.id}}</span> 
      <span><h3>Title: {{election.title}}</h3></span>
      {% if election.status=='open' %} 
      <span class="badge bg-success text-white">{{election.status}} </span>
      {% else %}
      <span class="badge bg-secondary text-white">{{election.status}} </span>

      {% endif %}
      <span class="badge bg-secondary text-white">Posts: {{post_count[election.id] or 0}} </span>
      <span><a href="{{url_for('main.vote',id=election.id)}}" class="btn btn-secondary">Vote</a></span>
    </div>
</div>

{% endfor %}
{% else %}
<p>Oops, it's not election season yet! Hold your horse.</p>


{%endif%}
{% endmacro %}

{%macro displayPostCard(election,post_list,candidate_dict,vote_status_dict,election_winners_dict,election_posts_results_dict) %}

{% for post in post_list %}
{% if post.election.status=='closed' %}
<div class="col-lg-6">
  <div class="card mb-3">

    <h2 class="d-flex justify-content-around"><span>{{post.title}}</span>  <span>Winner:  <span class="text-success"> {{election_winners_dict[post.id] or "No Winner"}}</span></span> </h2>

    {% for candidate in candidate_dict[post.id] %}
    <div class="d-flex justify-content-around align-items-center my-2 p-3">

      {% if candidate.user.profile_pic_path %}
    <span><img src="{{url_for('static',filename=candidate.user.profile_pic_path)}}" alt="" class="" height="96"></span>
      {% else%}

    <span><img src="{{url_for('static',filename='photos/avatar.png')}}" alt="" height="96"></span>


      {% endif %}
      <span>{{candidate.user.name}}</span>

      <span class="badge bg-secondary text-white">{{election_posts_results_dict[post.id][candidate.id] or 0}}  Votes </span>

    </div>
      {% endfor %}
   

  </div>

</div>

{% elif post.election.status=='open' %}

{% if not vote_status_dict[post.id] %}

<div class="col-lg-6">
  <div class="card mb-3">

    <h2>{{post.title}}</h2>

      {% for candidate in candidate_dict[post.id] %}
    <div class="d-flex justify-content-around align-items-center my-2 p-3">
      
      {% if candidate.user.profile_pic_path %}
    <span><img src="{{url_for('static',filename=candidate.user.profile_pic_path)}}" alt="" class="" height="96"></span>
      {% else%}

    <span><img src="{{url_for('static',filename='photos/avatar.png')}}" alt="" height="96"></span>


      {% endif %}

      <span>{{candidate.user.name}}</span>

      <span> <a href="{{url_for('main.cast_vote',id=post.election.id,post_id=post.id,candidate_id=candidate.id)}}" class="btn btn-secondary">Vote </a> </span>

    </div>
      {% endfor %}
      
    

  </div>

</div>
{% else%}

<div class="col-lg-6">
  <div class="card">

    <h2 class="d-flex justify-content-center">{{post.title}}</h2>
    <div class="d-flex flex-column justify-content-center align-items-center">
    <p>You have voted for this post.</p>

    <p>Status: <span class="badge bg-secondary"> Pending Announcement</span></p>
  </div>
  </div>

</div>

{% endif %}

{% endif %}


{% endfor %}

{% endmacro %}

{% macro displayFlash()  %}

<div class="flash-header d-flex justify-content-center container">
  {% with messages=get_flashed_messages() %}
  {% if get_flashed_messages(category_filter=["error"]) %}
  {% if messages %}

<ul class="flashes list-unstyled">
  {% for message in messages %}
  <li class="bg-danger feed-message text-white text-center fs-4 mt-2 rounded-3">{{message}}</li>
  {%endfor%}
</ul>
{%endif%}

{% elif get_flashed_messages(category_filter=["success"]) %}
  {% if messages %}

<ul class="flashes list-unstyled text-center rounded-3">
  {% for message in messages %}
  <li class="bg-success feed-message text-white text-center fs-4 mt-2 rounded-3">{{message}}</li>
  {%endfor%}
</ul>
{%endif%}
{%endif%}

{% endwith %}
</div>

{% endmacro %}

app/templates/main/newest.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{{url_for('static',filename='css/main/index.css')}}"> {% if title %}
    <title>Dashboard - {{ title }}</title>
    {% else %}
    <title>Dashboard-student</title>
    {% endif %}
</head>

<body>
    <!-- <div class="container-fluid"> -->
    <div class="nav1">
        <nav class="navbar navbar-expand-lg navbar-color bg-co">
            <div class="container">
                <a class="navbar-brand" href="#">Student &nbsp; <span id="dash">Dashboard</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav mr-auto">
                    </div>
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="#">Welcome,</a>
                        <a class="nav-item nav-link" href="#">Student</a>
                        <a class="nav-item nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <!-- ..content  -->
    <div class="container">
        <div class="getPostData">
            <div class="getPost">
                <div class="getPost-tle">
                    <h1>{{post.title}}</h1>
                </div>
            </div>
            {% for candidate in candidates %}
            <a href="">
                <div class="getCand">
                    <div class="get-cand-img">
                        <img src="{{url_for('static', filename='asset-images/user.png')}}" alt="">
                    </div>
                    <div class="get-cand-info">
                        <h3>
                            {{candidate.user.name}}
                        </h3>
                    </div>
                </div>
            </a>
            {%endfor%}
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>

</html>

app/templates/main/stdView_1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{{url_for('static',filename='css/main/index.css')}}"> {% if title %}
    <title>Dashboard - {{ title }}</title>
    {% else %}
    <title>Dashboard-student</title>
    {% endif %}
</head>

<body>
    <!-- <div class="container-fluid"> -->
    <div class="nav1">
        <nav class="navbar navbar-expand-lg navbar-color bg-co">
            <div class="container">
                <a class="navbar-brand" href="#">Student &nbsp; <span id="dash">Dashboard</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav mr-auto">
                    </div>

                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="#">Welcome,</a>
                        <a class="nav-item nav-link" href="#">Student</a>
                        <a class="nav-item nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <!-- ..content  -->
    <div class="container">
        <div class="ele-cont">
            <h1><span id="act">Active</span>&nbsp<span id="election">Elections</span><img src="../static/asset-images/hand-voting-ballot-box-icon-260nw-1342666157.jpg" style="height: 50px; width:50px;"></h1>
            <div class="vote">
                {% for elect in elections %}
                <div class="elect">
                    <div class="row">
                        <div class="col-md-1">
                            <div class="elect-id">
                                <p>{{elect.id}}</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <h2>{{elect.title}}</h2>
                        </div>
                        <div class="col-md-5">
                            <div class="date">
                                <p>{{elect.start_time}} - </p>
                                <p> {{elect.end_time}}</p>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <form action="{{url_for('main.submitElection',election_id=elect.id)}}" method="GET">
                                <button type="submit">Vote</button>
                            </form>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>

</html>

app/templates/main/std_footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link rel="stylesheet" href="{{url_for('static',filename='css/main/std_footer.css')}}">

    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    

</head>
<body>
<!--footer starts from here-->
<footer class="footer">
<div class="container bottom_border">
<div class="row">
<div class=" col-sm-4 col-md col-sm-4  col-12 col">
<h5 class="headin5_amrc col_white_amrc pt2">Find us</h5>
<!--headin5_amrc-->
<p class="mb10">The easiest application that allows students to vote for a candidate in a post in a school election.
</p>
<p><i class="fa fa-location-arrow"></i> 9878/25 sec 9 rohini 35 </p>
<p><i class="fa fa-phone"></i>  +91-9999878398  </p>
<p><i class="fa fa fa-envelope"></i> info@example.com  </p>


</div>



<div class=" col-sm-4 col-md  col-12 col">
<h5 class="headin5_amrc col_white_amrc pt2">Follow us</h5>
<!--headin5_amrc ends here-->

<ul class="footer_ul2_amrc">
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p><a href="#">https://www.lipsum.com/</a></p></li>
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p><a href="#">https://www.lipsum.com/</a></p></li>
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p><a href="#">https://www.lipsum.com/</a></p></li>
</ul>
<!--footer_ul2_amrc ends here-->
</div>
</div>
</div>



<!--foote_bottom_ul_amrc ends here-->
<p class="text-center">Copyright @2022 | by <a href="#">Group 1</a></p>

<ul class="social_footer_ul">
<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
<li><a href="#"><i class="fab fa-twitter"></i></a></li>
<li><a href="#"><i class="fab fa-linkedin"></i></a></li>
<li><a href="#"><i class="fab fa-instagram"></i></a></li>
</ul>
<!--social_footer_ul ends here-->
</div>

</footer>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

app/templates/main/vote.html
{% extends 'auth/base.html' %}
{% import 'main/macros.html' as macro %}
{% block nav %}
{% include 'auth/navbar.html' %}
{% endblock %}
{% block content %}

<div class="container">
  <h4 class="p-4">{{election.title}} Election <span class="bg-dark text-white p-2">{{election.start_time}}</span> - <span class="bg-dark text-white p-2">{{election.end_time}}</span></h4>
  <h1 class="text-center"><span id="act"> Posts</span>&nbsp<span id="election">List</span><img src="{{url_for('static',filename='asset-images/hand-voting-ballot-box-icon-260nw-1342666157.jpg')}}" style="height: 50px; width:50px;"></h1>

<div class="row">

  
{{macro.displayPostCard(election,posts,all_candidates,vote_status,election_winners,election_posts_results)}}


</div>

</div>

{% endblock %}